import Head from "next/head";
import Image from "next/image";
import styles from "../styles/index.module.scss";
import TypingText from "../components/TypingText";
import { motion, AnimatePresence } from "framer-motion";
import { useState, useEffect, useRef } from "react";
import useWindowWidth from "../hooks/useWindowWidth";
import Laser from "../components/laser";
export default function Home() {
  const [loading, setLoading] = useState(true);
  const [clicked, setClicked] = useState(false);
  const [leftEyePosition, setLeftEyePosition] = useState({ x: 0, y: 0 });
  const [rightEyePosition, setRightEyePosition] = useState({ x: 0, y: 0 });
  const [laserEyesActive, setLaserEyesActive] = useState(false);
  const [loadingAnimation, setLoadingAnimation] = useState(true);
  let wayPoints = [];
  const leftEyeRef = useRef(null);
  const rightEyeRef = useRef(null);
  const leftEyeDesktopRef = useRef(null);
  const rightEyeDesktopRef = useRef(null);
  const gifContainer = useRef(null);
  const width = useWindowWidth();
  const video = useRef(null);

  useEffect(() => {
    setTimeout(() => {
      setLoadingAnimation(false);
    }, 8000);
    setTimeout(() => {
      setLoading(false);
    }, 8100);
    // setTimeout(() => {
    //   setLaserEyesActive(true);
    // }, 20000);
    setTimeout(() => {
      video.current.play();
    }, 10000);
  }, []);

  const colors = ["#06ff29", "ff0000", "#06aeff", "#da06ff"];
  return (
    <>
      <Head>
        <title>The wormhole of fuckery...</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favidildo.png" />
      </Head>
      <video
        className={styles.backgroundVideo}
        ref={video}
        width={"100%"}
        height={"100%"}
        muted
      >
        <source src="video.mp4" type="video/mp4"></source>
      </video>
      <Image
        src={"/background.JPG"}
        layout="fill"
        objectFit="cover"
        objectPosition="center"
        priority={true}
        className={styles.mobileBackground}
      />
      <AnimatePresence exitBeforeEnter>
        {loading ? (
          <motion.div
            className={styles.loadingAnimation}
            key={"loadingContainer"}
            exit={{ opacity: 0 }}
            transition={{ duration: width > 1000 ? 4 : 2 }}
          >
            {loadingAnimation && (
              <div className={styles.loadingAnimationInner}>
                <img
                  src={"/loading.gif"}
                  className={styles.loadingAnimationImage}
                />
                <a
                  href="https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/62841633602125627004461028476566339821126370754397700221279471775592520613889"
                  className={styles.nftLink}
                  target="_blank"
                  rel="noreferrer"
                />
              </div>
            )}
          </motion.div>
        ) : (
          <>
            <Laser width={width} />
            <motion.div className={styles.typingTextContainer}>
              <TypingText
                text={
                  "Greetings, anon. I am DOOMape, sent by the overlord himself to guide you through the smog of web3. Your early arrival is most welcome and preparations are well underway. Pay careful attention to the overlord's official messenger @reducedtoclear_ that is the ONLY way we will contact you."
                }
                clicked={clicked}
                setClicked={(val) => setClicked(val)}
                angle={10}
                leftEyeRef={leftEyeRef}
                rightEyeRef={rightEyeRef}
              />
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </>
  );
}
