import Head from "next/head";
import Image from "next/image";
import styles from "../styles/index.module.scss";
import TypingText from "../components/TypingText";
import { motion } from "framer-motion";
import { useState, useEffect } from "react";

export default function Home() {
  const [loading, setLoading] = useState(true);
  const [clicked, setClicked] = useState(false);
  const [laserColour, setLaserColour] = useState("ff0000");
  useEffect(() => {
    setTimeout(() => {
      setLoading();
    }, 8000);
  }, []);
  const colors = ["#06ff29", "ff0000", "#06aeff", "#da06ff"];
  const laserLine = {
    fire: {
      width: 5000,
      transition: {
        duration: 0.5,
        delay: 1.5,
      },
    },
    width: {
      width: 5000,
    },
    stop: {
      width: 0,
      transition: {
        duration: 0.5,
      },
    },
  };

  const eyes = {
    fire: {
      opacity: 1,
      transition: {
        duration: 1,
      },
    },
    stop: {
      opacity: 0,
      transition: {
        duration: 1,
      },
    },
  };
  return (
    <div className={styles.container} onClick={() => setClicked(true)}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading ? (
        <div className={styles.loadingAnimation}>
          <div className={styles.loadingAnimationInner}>
            <img
              src={"/loading.gif"}
              className={styles.loadingAnimationImage}
            />
            <a
              href="https://opensea.io/assets/matic/0x2953399124f0cbb46d2cbacd8a89cf0599974963/62841633602125627004461028476566339821126370754397700221279471775592520613889"
              className={styles.nftLink}
              target="_blank"
              rel="noreferrer"
            />
          </div>
        </div>
      ) : (
        <>
          {" "}
          <div className={styles.introPageContainer}>
            <div className={styles.typingTextContainer}>
              <div className={styles.laserEyesContainer}>
                <div className={styles.eyesContainer}>
                  <div className={styles.eye}>
                    <motion.div
                      variants={eyes}
                      animate={clicked ? "fire" : "stop"}
                      className={styles.outerEye}
                      style={{ backgroundColor: laserColour }}
                    ></motion.div>
                    <motion.div
                      variants={eyes}
                      animate={clicked ? "fire" : "stop"}
                      className={styles.innerEye}
                    ></motion.div>
                  </div>
                  <div className={styles.laserContainer}>
                    <motion.div
                      variants={laserLine}
                      animate={clicked ? "fire" : "stop"}
                      className={styles.outerLine}
                      style={{ backgroundColor: laserColour }}
                      onAnimationComplete={() => {
                        // setLaserColour(colors[Math.floor(Math.random() * 4)]);
                        setClicked(false);
                      }}
                    ></motion.div>
                    <motion.div
                      variants={laserLine}
                      animate={clicked ? "fire" : "stop"}
                      className={styles.innerLine}
                    ></motion.div>
                  </div>
                </div>
                <div className={styles.eyesContainer}>
                  <div className={styles.eye}>
                    <motion.div
                      variants={eyes}
                      animate={clicked ? "fire" : "stop"}
                      className={styles.outerEye}
                      style={{ backgroundColor: laserColour }}
                    ></motion.div>
                    <motion.div
                      variants={eyes}
                      animate={clicked ? "fire" : "stop"}
                      className={styles.innerEye}
                    ></motion.div>
                  </div>
                  <div className={styles.laserContainer}>
                    <motion.div
                      variants={laserLine}
                      animate={clicked ? "fire" : "stop"}
                      className={styles.outerLine}
                      style={{ backgroundColor: laserColour }}
                    ></motion.div>
                    <motion.div
                      variants={laserLine}
                      animate={clicked ? "fire" : "stop"}
                      className={styles.innerLine}
                    ></motion.div>
                  </div>
                </div>
              </div>
              <TypingText
                text={
                  "Dark forces of the non-fungible kind are converging XX/XX/2022 @ 11:11PM EST..."
                }
              />

              {/* <Image
                src={"/testLogo.png"}
                width={200}
                height={200}
                className={styles.logo}
              /> */}
            </div>
          </div>
        </>
      )}
    </div>
  );
}
